### ISSUE TITLE
請問目前官方版本 Ubuntu 不是以思源黑體為預設字體嗎？

### ISSUE THREAD

**Issue by laichiaheng** [Not-That-Ubuntu-Taiwan-Community/Ubuntu-TW-Ubuntu#21]
如果不是，是否可以建議他們採用呢？

**Comment by brlin-tw** [comment]
[Bug #1468027 “change default CJK fonts to Noto CJK” : Bugs : language-selector package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/language-selector/+bug/1468027)
目前還不是，Ubuntu 上游已經在進行修正
