### ISSUE TITLE
看您的預覽圖，這似乎非思源黑體？

### ISSUE THREAD

**Issue by laichiaheng** [Not-That-Ubuntu-Taiwan-Community/Ubuntu-TW-Ubuntu#25]
![- unity xfce](https://cloud.githubusercontent.com/assets/9532105/13805968/8b8ea656-eb93-11e5-8496-8add0da66e59.png)
選取的「選」

**Comment by Vdragon** [comment]
目前的版本並未將思源黑體設為預設字型，只有安裝上去而已。

https://github.com/Ubuntu-Taiwan-Community/Ubuntu-TW-Ubuntu/tree/%E4%B8%BB%E8%A6%81%E9%96%8B%E7%99%BC%E5%88%86%E6%94%AF/%E4%BF%AE%E6%AD%A3/%E5%AE%89%E8%A3%9D%E7%AC%A6%E5%90%88%E5%8F%B0%E7%81%A3%E7%AD%86%E5%8A%83%E8%A6%8F%E7%AF%84%E7%9A%84%E5%AD%97%E5%9E%8B
