### ISSUE TITLE
在終端機上，英文輸入模式鍵盤對應錯誤

### ISSUE THREAD

**Issue by curtisyen74** [Not-That-Ubuntu-Taiwan-Community/Ubuntu-TW-Ubuntu#27]
按鍵U I O P J K L M , . / 等對應錯誤，
相關組合鑑也需一併再確認

顏千堤

**Comment by brlin-tw** [comment]
@curtisyen74 
您好
這比較像是無獨立數字鍵區的鍵盤數字鎖定(Numlock)狀態未停用下會出現的問題
請檢查鍵盤的數字鎖定狀態
